default: &default
  adapter: postgresql
  username: postgres
  password: root
  host: localhost
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: viki_tweet_development

test:
  <<: *default
  database: viki_tweet_test

production:
  <<: *default
  database: viki_tweet_production
  username: viki_tweet
  password: <%= ENV['ROR_SOCIAL_SCAFFOLD_DATABASE_PASSWORD'] %>
